---
# Ansible
ansible_become: yes

# User
username: kube

# K3s
k3s_version: v1.20.0+k3s2
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
